apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec: 
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: myprod
          labels:
            app: myapp
        spec:
         restartPolicy: OnFailure
         containers:
           - name: hello
             image: busybox
             args:
              - /bin/sh
              - -c
              - date; echo Hello k8s
