kind: Pod
apiVersion: v1
metadata:
  name: multiconpod
spec: 
 containers:
   - name: c01
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo hello world; sleep 10; done"]
   - name: c02
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo hiii; sleep 20; done"]  
